### ISSUE TITLE
program

### ISSUE THREAD

**Issue by RoySegall** [Gizra/drupalcamp#4]
The program of the camp will be table. This will be instead of the SERVICES.
- [x] Add sample responsive table
- [x] Update table with live content.
- [x] Create 2 template toggle show/hide ( progaram / add lecture contact form)
- [x] Create table for mobile / Desktop.
- [x] title link(color 1) lecture link(color 2)

**Comment by RoySegall** [comment]
Structure of the yml table:

```
- hour: 09:00 - 100:00
  title: Foo
  anchor: foo
  description: 

-
  - hour: 10:00 - 11:00
    title: Foo
    anchor: roy
    description: 

  - hour: 10:00 - 11:00
    title: Bar
    anchor: ran
    description: 

-
  - hour: 11:30 - 12:00
    title: Bar
    anchor: carlos
    description: 

  - hour: 11:30 - 12:00
    title: Bar
    anchor: ran
    description: 
```

when i click on the keynote title the description should appear. The description will gone when clicking on other page part.

The description name will lead us to to his profile section.
